unstable_features = true

group_imports = "StdExternalCrate"  # Default: Preserve
hex_literal_case = "Lower"  # Default: Preserve
imports_granularity = "Module"  # Default: Preserve
normalize_comments = true  # Default: false
normalize_doc_attributes = true  # Default: false
use_small_heuristics = "Max"  # Default: Default
version = "Two"  # Default: One
